image: maven:3.3-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  paths:
    - .m2/

before_script:
  - mkdir -p $HOME/.m2/

stages:
  - test
  - build
  - deploy

unit_test:
  stage: test
  script:
    - mvn clean test -B

.build: &build_template
  stage: build
  script:
    - mvn package -B

master_build:
  <<: *build_template
  only:
    - master
    - tags
  artifacts:
    expire_in: 1 month
    paths:
      - web/target/*.war
