package bz.sunlight.dao;

import bz.sunlight.entity.EnterpriseAccount;
import bz.sunlight.entity.EnterpriseAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnterpriseAccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int countByExample(EnterpriseAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int deleteByExample(EnterpriseAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int insert(EnterpriseAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int insertSelective(EnterpriseAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	List<EnterpriseAccount> selectByExample(EnterpriseAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	EnterpriseAccount selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") EnterpriseAccount record,
			@Param("example") EnterpriseAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") EnterpriseAccount record,
			@Param("example") EnterpriseAccountExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(EnterpriseAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise_account
	 * @mbggenerated
	 */
	int updateByPrimaryKey(EnterpriseAccount record);
}