package bz.sunlight.dao;

import bz.sunlight.entity.Enterprise;
import bz.sunlight.entity.EnterpriseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnterpriseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int countByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int deleteByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int insert(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int insertSelective(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	List<Enterprise> selectByExample(EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	Enterprise selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Enterprise record,
			@Param("example") EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Enterprise record,
			@Param("example") EnterpriseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Enterprise record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Enterprise record);
}