package bz.sunlight.dao;

import bz.sunlight.entity.AdPool;
import bz.sunlight.entity.AdPoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdPoolMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int countByExample(AdPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int deleteByExample(AdPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int insert(AdPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int insertSelective(AdPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	List<AdPool> selectByExample(AdPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	AdPool selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") AdPool record,
			@Param("example") AdPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") AdPool record,
			@Param("example") AdPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AdPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ad_pool
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AdPool record);
}