package bz.sunlight.dao;

import bz.sunlight.entity.Bill;
import bz.sunlight.entity.BillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int countByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int deleteByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int insert(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int insertSelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	List<Bill> selectByExample(BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	Bill selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Bill record,
			@Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Bill record,
			@Param("example") BillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Bill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Bill record);
}