package bz.sunlight.dao;

import bz.sunlight.entity.BusinessQueue;
import bz.sunlight.entity.BusinessQueueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int countByExample(BusinessQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int deleteByExample(BusinessQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int insert(BusinessQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int insertSelective(BusinessQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    List<BusinessQueue> selectByExample(BusinessQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    BusinessQueue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BusinessQueue record, @Param("example") BusinessQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BusinessQueue record, @Param("example") BusinessQueueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_queue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessQueue record);
}