package bz.sunlight.dao;

import bz.sunlight.entity.CallStateMsg;
import bz.sunlight.entity.CallStateMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallStateMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int countByExample(CallStateMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int deleteByExample(CallStateMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int insert(CallStateMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int insertSelective(CallStateMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    List<CallStateMsg> selectByExample(CallStateMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    CallStateMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CallStateMsg record, @Param("example") CallStateMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CallStateMsg record, @Param("example") CallStateMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CallStateMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_state_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CallStateMsg record);
}