package bz.sunlight.dao;

import bz.sunlight.entity.CallLog;
import bz.sunlight.entity.CallLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CallLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int countByExample(CallLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int deleteByExample(CallLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int insert(CallLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int insertSelective(CallLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	List<CallLog> selectByExample(CallLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	CallLog selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") CallLog record,
			@Param("example") CallLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") CallLog record,
			@Param("example") CallLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(CallLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table call_log
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CallLog record);
}