package bz.sunlight.dao;

import bz.sunlight.entity.DiscardSecretPool;
import bz.sunlight.entity.DiscardSecretPoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscardSecretPoolMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int countByExample(DiscardSecretPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int deleteByExample(DiscardSecretPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int insert(DiscardSecretPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int insertSelective(DiscardSecretPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	List<DiscardSecretPool> selectByExample(DiscardSecretPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	DiscardSecretPool selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") DiscardSecretPool record,
			@Param("example") DiscardSecretPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") DiscardSecretPool record,
			@Param("example") DiscardSecretPoolExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(DiscardSecretPool record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table discard_secret_pool
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DiscardSecretPool record);
}