package bz.sunlight.dao;

import bz.sunlight.dto.KeepSecretDTO;
import bz.sunlight.entity.KeepSecret;
import bz.sunlight.entity.KeepSecretExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface KeepSecretMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int countByExample(KeepSecretExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int deleteByExample(KeepSecretExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int insert(KeepSecret record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int insertSelective(KeepSecret record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	List<KeepSecret> selectByExample(KeepSecretExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	KeepSecret selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") KeepSecret record,
			@Param("example") KeepSecretExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") KeepSecret record,
			@Param("example") KeepSecretExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(KeepSecret record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table keep_secret
	 * @mbggenerated
	 */
	int updateByPrimaryKey(KeepSecret record);
	
//	List<KeepSecret> getKeepSecret(@Param("enterpirseId") String enterpirseId,@Param("keepStatus") Short keepStatus,@Param("status") Short status);
	
	List<KeepSecret> getKeepSecret(KeepSecretDTO keepSecretDTO);
	
	int  getKeepSecretCount(KeepSecretDTO keepSecretDTO);
}