package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class ImportDataExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table import_data
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table import_data
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table import_data
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public ImportDataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table import_data
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table import_data
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCopIdIsNull() {
			addCriterion("cop_id is null");
			return (Criteria) this;
		}

		public Criteria andCopIdIsNotNull() {
			addCriterion("cop_id is not null");
			return (Criteria) this;
		}

		public Criteria andCopIdEqualTo(String value) {
			addCriterion("cop_id =", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdNotEqualTo(String value) {
			addCriterion("cop_id <>", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdGreaterThan(String value) {
			addCriterion("cop_id >", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdGreaterThanOrEqualTo(String value) {
			addCriterion("cop_id >=", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdLessThan(String value) {
			addCriterion("cop_id <", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdLessThanOrEqualTo(String value) {
			addCriterion("cop_id <=", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdLike(String value) {
			addCriterion("cop_id like", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdNotLike(String value) {
			addCriterion("cop_id not like", value, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdIn(List<String> values) {
			addCriterion("cop_id in", values, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdNotIn(List<String> values) {
			addCriterion("cop_id not in", values, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdBetween(String value1, String value2) {
			addCriterion("cop_id between", value1, value2, "copId");
			return (Criteria) this;
		}

		public Criteria andCopIdNotBetween(String value1, String value2) {
			addCriterion("cop_id not between", value1, value2, "copId");
			return (Criteria) this;
		}

		public Criteria andSopIdIsNull() {
			addCriterion("sop_id is null");
			return (Criteria) this;
		}

		public Criteria andSopIdIsNotNull() {
			addCriterion("sop_id is not null");
			return (Criteria) this;
		}

		public Criteria andSopIdEqualTo(String value) {
			addCriterion("sop_id =", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdNotEqualTo(String value) {
			addCriterion("sop_id <>", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdGreaterThan(String value) {
			addCriterion("sop_id >", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdGreaterThanOrEqualTo(String value) {
			addCriterion("sop_id >=", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdLessThan(String value) {
			addCriterion("sop_id <", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdLessThanOrEqualTo(String value) {
			addCriterion("sop_id <=", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdLike(String value) {
			addCriterion("sop_id like", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdNotLike(String value) {
			addCriterion("sop_id not like", value, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdIn(List<String> values) {
			addCriterion("sop_id in", values, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdNotIn(List<String> values) {
			addCriterion("sop_id not in", values, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdBetween(String value1, String value2) {
			addCriterion("sop_id between", value1, value2, "sopId");
			return (Criteria) this;
		}

		public Criteria andSopIdNotBetween(String value1, String value2) {
			addCriterion("sop_id not between", value1, value2, "sopId");
			return (Criteria) this;
		}

		public Criteria andTimeStampIsNull() {
			addCriterion("time_stamp is null");
			return (Criteria) this;
		}

		public Criteria andTimeStampIsNotNull() {
			addCriterion("time_stamp is not null");
			return (Criteria) this;
		}

		public Criteria andTimeStampEqualTo(String value) {
			addCriterion("time_stamp =", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotEqualTo(String value) {
			addCriterion("time_stamp <>", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampGreaterThan(String value) {
			addCriterion("time_stamp >", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampGreaterThanOrEqualTo(String value) {
			addCriterion("time_stamp >=", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLessThan(String value) {
			addCriterion("time_stamp <", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLessThanOrEqualTo(String value) {
			addCriterion("time_stamp <=", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampLike(String value) {
			addCriterion("time_stamp like", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotLike(String value) {
			addCriterion("time_stamp not like", value, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampIn(List<String> values) {
			addCriterion("time_stamp in", values, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotIn(List<String> values) {
			addCriterion("time_stamp not in", values, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampBetween(String value1, String value2) {
			addCriterion("time_stamp between", value1, value2, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andTimeStampNotBetween(String value1, String value2) {
			addCriterion("time_stamp not between", value1, value2, "timeStamp");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdIsNull() {
			addCriterion("correlate_id is null");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdIsNotNull() {
			addCriterion("correlate_id is not null");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdEqualTo(String value) {
			addCriterion("correlate_id =", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdNotEqualTo(String value) {
			addCriterion("correlate_id <>", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdGreaterThan(String value) {
			addCriterion("correlate_id >", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdGreaterThanOrEqualTo(String value) {
			addCriterion("correlate_id >=", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdLessThan(String value) {
			addCriterion("correlate_id <", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdLessThanOrEqualTo(String value) {
			addCriterion("correlate_id <=", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdLike(String value) {
			addCriterion("correlate_id like", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdNotLike(String value) {
			addCriterion("correlate_id not like", value, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdIn(List<String> values) {
			addCriterion("correlate_id in", values, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdNotIn(List<String> values) {
			addCriterion("correlate_id not in", values, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdBetween(String value1, String value2) {
			addCriterion("correlate_id between", value1, value2, "correlateId");
			return (Criteria) this;
		}

		public Criteria andCorrelateIdNotBetween(String value1, String value2) {
			addCriterion("correlate_id not between", value1, value2,
					"correlateId");
			return (Criteria) this;
		}

		public Criteria andHandleStatusIsNull() {
			addCriterion("handle_status is null");
			return (Criteria) this;
		}

		public Criteria andHandleStatusIsNotNull() {
			addCriterion("handle_status is not null");
			return (Criteria) this;
		}

		public Criteria andHandleStatusEqualTo(Short value) {
			addCriterion("handle_status =", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusNotEqualTo(Short value) {
			addCriterion("handle_status <>", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusGreaterThan(Short value) {
			addCriterion("handle_status >", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("handle_status >=", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusLessThan(Short value) {
			addCriterion("handle_status <", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusLessThanOrEqualTo(Short value) {
			addCriterion("handle_status <=", value, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusIn(List<Short> values) {
			addCriterion("handle_status in", values, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusNotIn(List<Short> values) {
			addCriterion("handle_status not in", values, "handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusBetween(Short value1, Short value2) {
			addCriterion("handle_status between", value1, value2,
					"handleStatus");
			return (Criteria) this;
		}

		public Criteria andHandleStatusNotBetween(Short value1, Short value2) {
			addCriterion("handle_status not between", value1, value2,
					"handleStatus");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlIsNull() {
			addCriterion("content_mngTXTURL is null");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlIsNotNull() {
			addCriterion("content_mngTXTURL is not null");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlEqualTo(String value) {
			addCriterion("content_mngTXTURL =", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlNotEqualTo(String value) {
			addCriterion("content_mngTXTURL <>", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlGreaterThan(String value) {
			addCriterion("content_mngTXTURL >", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlGreaterThanOrEqualTo(String value) {
			addCriterion("content_mngTXTURL >=", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlLessThan(String value) {
			addCriterion("content_mngTXTURL <", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlLessThanOrEqualTo(String value) {
			addCriterion("content_mngTXTURL <=", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlLike(String value) {
			addCriterion("content_mngTXTURL like", value, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlNotLike(String value) {
			addCriterion("content_mngTXTURL not like", value,
					"contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlIn(List<String> values) {
			addCriterion("content_mngTXTURL in", values, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlNotIn(List<String> values) {
			addCriterion("content_mngTXTURL not in", values, "contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlBetween(String value1, String value2) {
			addCriterion("content_mngTXTURL between", value1, value2,
					"contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andContentMngtxturlNotBetween(String value1,
				String value2) {
			addCriterion("content_mngTXTURL not between", value1, value2,
					"contentMngtxturl");
			return (Criteria) this;
		}

		public Criteria andFileUrlIsNull() {
			addCriterion("file_url is null");
			return (Criteria) this;
		}

		public Criteria andFileUrlIsNotNull() {
			addCriterion("file_url is not null");
			return (Criteria) this;
		}

		public Criteria andFileUrlEqualTo(String value) {
			addCriterion("file_url =", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlNotEqualTo(String value) {
			addCriterion("file_url <>", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlGreaterThan(String value) {
			addCriterion("file_url >", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlGreaterThanOrEqualTo(String value) {
			addCriterion("file_url >=", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlLessThan(String value) {
			addCriterion("file_url <", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlLessThanOrEqualTo(String value) {
			addCriterion("file_url <=", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlLike(String value) {
			addCriterion("file_url like", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlNotLike(String value) {
			addCriterion("file_url not like", value, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlIn(List<String> values) {
			addCriterion("file_url in", values, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlNotIn(List<String> values) {
			addCriterion("file_url not in", values, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlBetween(String value1, String value2) {
			addCriterion("file_url between", value1, value2, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andFileUrlNotBetween(String value1, String value2) {
			addCriterion("file_url not between", value1, value2, "fileUrl");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table import_data
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table import_data
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}