package bz.sunlight.entity;

import java.util.Date;

public class ImportData {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.cop_id
	 * @mbggenerated
	 */
	private String copId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.sop_id
	 * @mbggenerated
	 */
	private String sopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.time_stamp
	 * @mbggenerated
	 */
	private String timeStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.correlate_id
	 * @mbggenerated
	 */
	private String correlateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.handle_status
	 * @mbggenerated
	 */
	private Short handleStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.content_mngTXTURL
	 * @mbggenerated
	 */
	private String contentMngtxturl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.file_url
	 * @mbggenerated
	 */
	private String fileUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column import_data.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.id
	 * @return  the value of import_data.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.id
	 * @param id  the value for import_data.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.cop_id
	 * @return  the value of import_data.cop_id
	 * @mbggenerated
	 */
	public String getCopId() {
		return copId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.cop_id
	 * @param copId  the value for import_data.cop_id
	 * @mbggenerated
	 */
	public void setCopId(String copId) {
		this.copId = copId == null ? null : copId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.sop_id
	 * @return  the value of import_data.sop_id
	 * @mbggenerated
	 */
	public String getSopId() {
		return sopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.sop_id
	 * @param sopId  the value for import_data.sop_id
	 * @mbggenerated
	 */
	public void setSopId(String sopId) {
		this.sopId = sopId == null ? null : sopId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.time_stamp
	 * @return  the value of import_data.time_stamp
	 * @mbggenerated
	 */
	public String getTimeStamp() {
		return timeStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.time_stamp
	 * @param timeStamp  the value for import_data.time_stamp
	 * @mbggenerated
	 */
	public void setTimeStamp(String timeStamp) {
		this.timeStamp = timeStamp == null ? null : timeStamp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.correlate_id
	 * @return  the value of import_data.correlate_id
	 * @mbggenerated
	 */
	public String getCorrelateId() {
		return correlateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.correlate_id
	 * @param correlateId  the value for import_data.correlate_id
	 * @mbggenerated
	 */
	public void setCorrelateId(String correlateId) {
		this.correlateId = correlateId == null ? null : correlateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.handle_status
	 * @return  the value of import_data.handle_status
	 * @mbggenerated
	 */
	public Short getHandleStatus() {
		return handleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.handle_status
	 * @param handleStatus  the value for import_data.handle_status
	 * @mbggenerated
	 */
	public void setHandleStatus(Short handleStatus) {
		this.handleStatus = handleStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.content_mngTXTURL
	 * @return  the value of import_data.content_mngTXTURL
	 * @mbggenerated
	 */
	public String getContentMngtxturl() {
		return contentMngtxturl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.content_mngTXTURL
	 * @param contentMngtxturl  the value for import_data.content_mngTXTURL
	 * @mbggenerated
	 */
	public void setContentMngtxturl(String contentMngtxturl) {
		this.contentMngtxturl = contentMngtxturl == null ? null
				: contentMngtxturl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.file_url
	 * @return  the value of import_data.file_url
	 * @mbggenerated
	 */
	public String getFileUrl() {
		return fileUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.file_url
	 * @param fileUrl  the value for import_data.file_url
	 * @mbggenerated
	 */
	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl == null ? null : fileUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column import_data.create_time
	 * @return  the value of import_data.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column import_data.create_time
	 * @param createTime  the value for import_data.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}