package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.List;

public class EnterpriseExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table enterprise
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table enterprise
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table enterprise
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public EnterpriseExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table enterprise
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andShortNameIsNull() {
			addCriterion("short_name is null");
			return (Criteria) this;
		}

		public Criteria andShortNameIsNotNull() {
			addCriterion("short_name is not null");
			return (Criteria) this;
		}

		public Criteria andShortNameEqualTo(String value) {
			addCriterion("short_name =", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameNotEqualTo(String value) {
			addCriterion("short_name <>", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameGreaterThan(String value) {
			addCriterion("short_name >", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameGreaterThanOrEqualTo(String value) {
			addCriterion("short_name >=", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameLessThan(String value) {
			addCriterion("short_name <", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameLessThanOrEqualTo(String value) {
			addCriterion("short_name <=", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameLike(String value) {
			addCriterion("short_name like", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameNotLike(String value) {
			addCriterion("short_name not like", value, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameIn(List<String> values) {
			addCriterion("short_name in", values, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameNotIn(List<String> values) {
			addCriterion("short_name not in", values, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameBetween(String value1, String value2) {
			addCriterion("short_name between", value1, value2, "shortName");
			return (Criteria) this;
		}

		public Criteria andShortNameNotBetween(String value1, String value2) {
			addCriterion("short_name not between", value1, value2, "shortName");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNull() {
			addCriterion("industry is null");
			return (Criteria) this;
		}

		public Criteria andIndustryIsNotNull() {
			addCriterion("industry is not null");
			return (Criteria) this;
		}

		public Criteria andIndustryEqualTo(Short value) {
			addCriterion("industry =", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotEqualTo(Short value) {
			addCriterion("industry <>", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThan(Short value) {
			addCriterion("industry >", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryGreaterThanOrEqualTo(Short value) {
			addCriterion("industry >=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThan(Short value) {
			addCriterion("industry <", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryLessThanOrEqualTo(Short value) {
			addCriterion("industry <=", value, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryIn(List<Short> values) {
			addCriterion("industry in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotIn(List<Short> values) {
			addCriterion("industry not in", values, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryBetween(Short value1, Short value2) {
			addCriterion("industry between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andIndustryNotBetween(Short value1, Short value2) {
			addCriterion("industry not between", value1, value2, "industry");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andBankIsNull() {
			addCriterion("bank is null");
			return (Criteria) this;
		}

		public Criteria andBankIsNotNull() {
			addCriterion("bank is not null");
			return (Criteria) this;
		}

		public Criteria andBankEqualTo(String value) {
			addCriterion("bank =", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotEqualTo(String value) {
			addCriterion("bank <>", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankGreaterThan(String value) {
			addCriterion("bank >", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankGreaterThanOrEqualTo(String value) {
			addCriterion("bank >=", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLessThan(String value) {
			addCriterion("bank <", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLessThanOrEqualTo(String value) {
			addCriterion("bank <=", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankLike(String value) {
			addCriterion("bank like", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotLike(String value) {
			addCriterion("bank not like", value, "bank");
			return (Criteria) this;
		}

		public Criteria andBankIn(List<String> values) {
			addCriterion("bank in", values, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotIn(List<String> values) {
			addCriterion("bank not in", values, "bank");
			return (Criteria) this;
		}

		public Criteria andBankBetween(String value1, String value2) {
			addCriterion("bank between", value1, value2, "bank");
			return (Criteria) this;
		}

		public Criteria andBankNotBetween(String value1, String value2) {
			addCriterion("bank not between", value1, value2, "bank");
			return (Criteria) this;
		}

		public Criteria andBillingAddressIsNull() {
			addCriterion("billing_address is null");
			return (Criteria) this;
		}

		public Criteria andBillingAddressIsNotNull() {
			addCriterion("billing_address is not null");
			return (Criteria) this;
		}

		public Criteria andBillingAddressEqualTo(String value) {
			addCriterion("billing_address =", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressNotEqualTo(String value) {
			addCriterion("billing_address <>", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressGreaterThan(String value) {
			addCriterion("billing_address >", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressGreaterThanOrEqualTo(String value) {
			addCriterion("billing_address >=", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressLessThan(String value) {
			addCriterion("billing_address <", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressLessThanOrEqualTo(String value) {
			addCriterion("billing_address <=", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressLike(String value) {
			addCriterion("billing_address like", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressNotLike(String value) {
			addCriterion("billing_address not like", value, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressIn(List<String> values) {
			addCriterion("billing_address in", values, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressNotIn(List<String> values) {
			addCriterion("billing_address not in", values, "billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressBetween(String value1, String value2) {
			addCriterion("billing_address between", value1, value2,
					"billingAddress");
			return (Criteria) this;
		}

		public Criteria andBillingAddressNotBetween(String value1, String value2) {
			addCriterion("billing_address not between", value1, value2,
					"billingAddress");
			return (Criteria) this;
		}

		public Criteria andBankAccountIsNull() {
			addCriterion("bank_account is null");
			return (Criteria) this;
		}

		public Criteria andBankAccountIsNotNull() {
			addCriterion("bank_account is not null");
			return (Criteria) this;
		}

		public Criteria andBankAccountEqualTo(String value) {
			addCriterion("bank_account =", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotEqualTo(String value) {
			addCriterion("bank_account <>", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountGreaterThan(String value) {
			addCriterion("bank_account >", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
			addCriterion("bank_account >=", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLessThan(String value) {
			addCriterion("bank_account <", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLessThanOrEqualTo(String value) {
			addCriterion("bank_account <=", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountLike(String value) {
			addCriterion("bank_account like", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotLike(String value) {
			addCriterion("bank_account not like", value, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountIn(List<String> values) {
			addCriterion("bank_account in", values, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotIn(List<String> values) {
			addCriterion("bank_account not in", values, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountBetween(String value1, String value2) {
			addCriterion("bank_account between", value1, value2, "bankAccount");
			return (Criteria) this;
		}

		public Criteria andBankAccountNotBetween(String value1, String value2) {
			addCriterion("bank_account not between", value1, value2,
					"bankAccount");
			return (Criteria) this;
		}

		public Criteria andTaxNumberIsNull() {
			addCriterion("tax_number is null");
			return (Criteria) this;
		}

		public Criteria andTaxNumberIsNotNull() {
			addCriterion("tax_number is not null");
			return (Criteria) this;
		}

		public Criteria andTaxNumberEqualTo(String value) {
			addCriterion("tax_number =", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberNotEqualTo(String value) {
			addCriterion("tax_number <>", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberGreaterThan(String value) {
			addCriterion("tax_number >", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberGreaterThanOrEqualTo(String value) {
			addCriterion("tax_number >=", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberLessThan(String value) {
			addCriterion("tax_number <", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberLessThanOrEqualTo(String value) {
			addCriterion("tax_number <=", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberLike(String value) {
			addCriterion("tax_number like", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberNotLike(String value) {
			addCriterion("tax_number not like", value, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberIn(List<String> values) {
			addCriterion("tax_number in", values, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberNotIn(List<String> values) {
			addCriterion("tax_number not in", values, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberBetween(String value1, String value2) {
			addCriterion("tax_number between", value1, value2, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTaxNumberNotBetween(String value1, String value2) {
			addCriterion("tax_number not between", value1, value2, "taxNumber");
			return (Criteria) this;
		}

		public Criteria andTelIsNull() {
			addCriterion("tel is null");
			return (Criteria) this;
		}

		public Criteria andTelIsNotNull() {
			addCriterion("tel is not null");
			return (Criteria) this;
		}

		public Criteria andTelEqualTo(String value) {
			addCriterion("tel =", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotEqualTo(String value) {
			addCriterion("tel <>", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThan(String value) {
			addCriterion("tel >", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelGreaterThanOrEqualTo(String value) {
			addCriterion("tel >=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThan(String value) {
			addCriterion("tel <", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLessThanOrEqualTo(String value) {
			addCriterion("tel <=", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelLike(String value) {
			addCriterion("tel like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotLike(String value) {
			addCriterion("tel not like", value, "tel");
			return (Criteria) this;
		}

		public Criteria andTelIn(List<String> values) {
			addCriterion("tel in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotIn(List<String> values) {
			addCriterion("tel not in", values, "tel");
			return (Criteria) this;
		}

		public Criteria andTelBetween(String value1, String value2) {
			addCriterion("tel between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andTelNotBetween(String value1, String value2) {
			addCriterion("tel not between", value1, value2, "tel");
			return (Criteria) this;
		}

		public Criteria andContactNameIsNull() {
			addCriterion("contact_name is null");
			return (Criteria) this;
		}

		public Criteria andContactNameIsNotNull() {
			addCriterion("contact_name is not null");
			return (Criteria) this;
		}

		public Criteria andContactNameEqualTo(String value) {
			addCriterion("contact_name =", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameNotEqualTo(String value) {
			addCriterion("contact_name <>", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameGreaterThan(String value) {
			addCriterion("contact_name >", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameGreaterThanOrEqualTo(String value) {
			addCriterion("contact_name >=", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameLessThan(String value) {
			addCriterion("contact_name <", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameLessThanOrEqualTo(String value) {
			addCriterion("contact_name <=", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameLike(String value) {
			addCriterion("contact_name like", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameNotLike(String value) {
			addCriterion("contact_name not like", value, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameIn(List<String> values) {
			addCriterion("contact_name in", values, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameNotIn(List<String> values) {
			addCriterion("contact_name not in", values, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameBetween(String value1, String value2) {
			addCriterion("contact_name between", value1, value2, "contactName");
			return (Criteria) this;
		}

		public Criteria andContactNameNotBetween(String value1, String value2) {
			addCriterion("contact_name not between", value1, value2,
					"contactName");
			return (Criteria) this;
		}

		public Criteria andContactMobileIsNull() {
			addCriterion("contact_mobile is null");
			return (Criteria) this;
		}

		public Criteria andContactMobileIsNotNull() {
			addCriterion("contact_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andContactMobileEqualTo(String value) {
			addCriterion("contact_mobile =", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotEqualTo(String value) {
			addCriterion("contact_mobile <>", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileGreaterThan(String value) {
			addCriterion("contact_mobile >", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileGreaterThanOrEqualTo(String value) {
			addCriterion("contact_mobile >=", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLessThan(String value) {
			addCriterion("contact_mobile <", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLessThanOrEqualTo(String value) {
			addCriterion("contact_mobile <=", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileLike(String value) {
			addCriterion("contact_mobile like", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotLike(String value) {
			addCriterion("contact_mobile not like", value, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileIn(List<String> values) {
			addCriterion("contact_mobile in", values, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotIn(List<String> values) {
			addCriterion("contact_mobile not in", values, "contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileBetween(String value1, String value2) {
			addCriterion("contact_mobile between", value1, value2,
					"contactMobile");
			return (Criteria) this;
		}

		public Criteria andContactMobileNotBetween(String value1, String value2) {
			addCriterion("contact_mobile not between", value1, value2,
					"contactMobile");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("brand_id is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(String value) {
			addCriterion("brand_id =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(String value) {
			addCriterion("brand_id <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(String value) {
			addCriterion("brand_id >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
			addCriterion("brand_id >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(String value) {
			addCriterion("brand_id <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(String value) {
			addCriterion("brand_id <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLike(String value) {
			addCriterion("brand_id like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotLike(String value) {
			addCriterion("brand_id not like", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<String> values) {
			addCriterion("brand_id in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<String> values) {
			addCriterion("brand_id not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(String value1, String value2) {
			addCriterion("brand_id between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(String value1, String value2) {
			addCriterion("brand_id not between", value1, value2, "brandId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table enterprise
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}