package bz.sunlight.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EnterpriseAccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.enterpirse_id
	 * @mbggenerated
	 */
	private String enterpirseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.account_balance
	 * @mbggenerated
	 */
	private Double accountBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.called_quantity
	 * @mbggenerated
	 */
	private Integer calledQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.open_time
	 * @mbggenerated
	 */
	private Date openTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column enterprise_account.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.id
	 * @return  the value of enterprise_account.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.id
	 * @param id  the value for enterprise_account.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.enterpirse_id
	 * @return  the value of enterprise_account.enterpirse_id
	 * @mbggenerated
	 */
	public String getEnterpirseId() {
		return enterpirseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.enterpirse_id
	 * @param enterpirseId  the value for enterprise_account.enterpirse_id
	 * @mbggenerated
	 */
	public void setEnterpirseId(String enterpirseId) {
		this.enterpirseId = enterpirseId == null ? null : enterpirseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.account_balance
	 * @return  the value of enterprise_account.account_balance
	 * @mbggenerated
	 */
	public Double getAccountBalance() {
		return accountBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.account_balance
	 * @param accountBalance  the value for enterprise_account.account_balance
	 * @mbggenerated
	 */
	public void setAccountBalance(Double accountBalance) {
		this.accountBalance = accountBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.called_quantity
	 * @return  the value of enterprise_account.called_quantity
	 * @mbggenerated
	 */
	public Integer getCalledQuantity() {
		return calledQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.called_quantity
	 * @param calledQuantity  the value for enterprise_account.called_quantity
	 * @mbggenerated
	 */
	public void setCalledQuantity(Integer calledQuantity) {
		this.calledQuantity = calledQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.open_time
	 * @return  the value of enterprise_account.open_time
	 * @mbggenerated
	 */
	public Date getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.open_time
	 * @param openTime  the value for enterprise_account.open_time
	 * @mbggenerated
	 */
	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.status
	 * @return  the value of enterprise_account.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.status
	 * @param status  the value for enterprise_account.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column enterprise_account.create_time
	 * @return  the value of enterprise_account.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column enterprise_account.create_time
	 * @param createTime  the value for enterprise_account.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}