package bz.sunlight.entity;

import java.util.Date;

public class UserInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.gender
	 * @mbggenerated
	 */
	private Short gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.job_number
	 * @mbggenerated
	 */
	private String jobNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.position
	 * @mbggenerated
	 */
	private Short position;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.caller_mobile
	 * @mbggenerated
	 */
	private String callerMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.id
	 * @return  the value of user_info.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.id
	 * @param id  the value for user_info.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.enterprise_id
	 * @return  the value of user_info.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.enterprise_id
	 * @param enterpriseId  the value for user_info.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.name
	 * @return  the value of user_info.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.name
	 * @param name  the value for user_info.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.gender
	 * @return  the value of user_info.gender
	 * @mbggenerated
	 */
	public Short getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.gender
	 * @param gender  the value for user_info.gender
	 * @mbggenerated
	 */
	public void setGender(Short gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.job_number
	 * @return  the value of user_info.job_number
	 * @mbggenerated
	 */
	public String getJobNumber() {
		return jobNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.job_number
	 * @param jobNumber  the value for user_info.job_number
	 * @mbggenerated
	 */
	public void setJobNumber(String jobNumber) {
		this.jobNumber = jobNumber == null ? null : jobNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.position
	 * @return  the value of user_info.position
	 * @mbggenerated
	 */
	public Short getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.position
	 * @param position  the value for user_info.position
	 * @mbggenerated
	 */
	public void setPosition(Short position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.mobile
	 * @return  the value of user_info.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.mobile
	 * @param mobile  the value for user_info.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.caller_mobile
	 * @return  the value of user_info.caller_mobile
	 * @mbggenerated
	 */
	public String getCallerMobile() {
		return callerMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.caller_mobile
	 * @param callerMobile  the value for user_info.caller_mobile
	 * @mbggenerated
	 */
	public void setCallerMobile(String callerMobile) {
		this.callerMobile = callerMobile == null ? null : callerMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.create_time
	 * @return  the value of user_info.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.create_time
	 * @param createTime  the value for user_info.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}