package bz.sunlight.entity;

import java.math.BigDecimal;

public class BusinessRule {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.consumption_mini
	 * @mbggenerated
	 */
	private Double consumptionMini;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.call_price
	 * @mbggenerated
	 */
	private Double callPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.call_second
	 * @mbggenerated
	 */
	private Short callSecond;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.keep_price
	 * @mbggenerated
	 */
	private Double keepPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.remind_balance
	 * @mbggenerated
	 */
	private Double remindBalance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.seat_price
	 * @mbggenerated
	 */
	private Double seatPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business_rule.discard_rule
	 * @mbggenerated
	 */
	private String discardRule;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.id
	 * @return  the value of business_rule.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.id
	 * @param id  the value for business_rule.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.consumption_mini
	 * @return  the value of business_rule.consumption_mini
	 * @mbggenerated
	 */
	public Double getConsumptionMini() {
		return consumptionMini;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.consumption_mini
	 * @param consumptionMini  the value for business_rule.consumption_mini
	 * @mbggenerated
	 */
	public void setConsumptionMini(Double consumptionMini) {
		this.consumptionMini = consumptionMini;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.call_price
	 * @return  the value of business_rule.call_price
	 * @mbggenerated
	 */
	public Double getCallPrice() {
		return callPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.call_price
	 * @param callPrice  the value for business_rule.call_price
	 * @mbggenerated
	 */
	public void setCallPrice(Double callPrice) {
		this.callPrice = callPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.call_second
	 * @return  the value of business_rule.call_second
	 * @mbggenerated
	 */
	public Short getCallSecond() {
		return callSecond;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.call_second
	 * @param callSecond  the value for business_rule.call_second
	 * @mbggenerated
	 */
	public void setCallSecond(Short callSecond) {
		this.callSecond = callSecond;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.keep_price
	 * @return  the value of business_rule.keep_price
	 * @mbggenerated
	 */
	public Double getKeepPrice() {
		return keepPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.keep_price
	 * @param keepPrice  the value for business_rule.keep_price
	 * @mbggenerated
	 */
	public void setKeepPrice(Double keepPrice) {
		this.keepPrice = keepPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.remind_balance
	 * @return  the value of business_rule.remind_balance
	 * @mbggenerated
	 */
	public Double getRemindBalance() {
		return remindBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.remind_balance
	 * @param remindBalance  the value for business_rule.remind_balance
	 * @mbggenerated
	 */
	public void setRemindBalance(Double remindBalance) {
		this.remindBalance = remindBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.seat_price
	 * @return  the value of business_rule.seat_price
	 * @mbggenerated
	 */
	public Double getSeatPrice() {
		return seatPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.seat_price
	 * @param seatPrice  the value for business_rule.seat_price
	 * @mbggenerated
	 */
	public void setSeatPrice(Double seatPrice) {
		this.seatPrice = seatPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business_rule.discard_rule
	 * @return  the value of business_rule.discard_rule
	 * @mbggenerated
	 */
	public String getDiscardRule() {
		return discardRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business_rule.discard_rule
	 * @param discardRule  the value for business_rule.discard_rule
	 * @mbggenerated
	 */
	public void setDiscardRule(String discardRule) {
		this.discardRule = discardRule == null ? null : discardRule.trim();
	}
}