package bz.sunlight.entity;

import java.util.Date;

public class AdPool {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.ad
	 * @mbggenerated
	 */
	private String ad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.industry_tag1
	 * @mbggenerated
	 */
	private String industryTag1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.industry_tag2
	 * @mbggenerated
	 */
	private String industryTag2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.industry_tag3
	 * @mbggenerated
	 */
	private String industryTag3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.industry_tag4
	 * @mbggenerated
	 */
	private String industryTag4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.industry_tag5
	 * @mbggenerated
	 */
	private String industryTag5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ad_pool.status
	 * @mbggenerated
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.id
	 * @return  the value of ad_pool.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.id
	 * @param id  the value for ad_pool.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.ad
	 * @return  the value of ad_pool.ad
	 * @mbggenerated
	 */
	public String getAd() {
		return ad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.ad
	 * @param ad  the value for ad_pool.ad
	 * @mbggenerated
	 */
	public void setAd(String ad) {
		this.ad = ad == null ? null : ad.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.industry_tag1
	 * @return  the value of ad_pool.industry_tag1
	 * @mbggenerated
	 */
	public String getIndustryTag1() {
		return industryTag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.industry_tag1
	 * @param industryTag1  the value for ad_pool.industry_tag1
	 * @mbggenerated
	 */
	public void setIndustryTag1(String industryTag1) {
		this.industryTag1 = industryTag1 == null ? null : industryTag1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.industry_tag2
	 * @return  the value of ad_pool.industry_tag2
	 * @mbggenerated
	 */
	public String getIndustryTag2() {
		return industryTag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.industry_tag2
	 * @param industryTag2  the value for ad_pool.industry_tag2
	 * @mbggenerated
	 */
	public void setIndustryTag2(String industryTag2) {
		this.industryTag2 = industryTag2 == null ? null : industryTag2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.industry_tag3
	 * @return  the value of ad_pool.industry_tag3
	 * @mbggenerated
	 */
	public String getIndustryTag3() {
		return industryTag3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.industry_tag3
	 * @param industryTag3  the value for ad_pool.industry_tag3
	 * @mbggenerated
	 */
	public void setIndustryTag3(String industryTag3) {
		this.industryTag3 = industryTag3 == null ? null : industryTag3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.industry_tag4
	 * @return  the value of ad_pool.industry_tag4
	 * @mbggenerated
	 */
	public String getIndustryTag4() {
		return industryTag4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.industry_tag4
	 * @param industryTag4  the value for ad_pool.industry_tag4
	 * @mbggenerated
	 */
	public void setIndustryTag4(String industryTag4) {
		this.industryTag4 = industryTag4 == null ? null : industryTag4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.industry_tag5
	 * @return  the value of ad_pool.industry_tag5
	 * @mbggenerated
	 */
	public String getIndustryTag5() {
		return industryTag5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.industry_tag5
	 * @param industryTag5  the value for ad_pool.industry_tag5
	 * @mbggenerated
	 */
	public void setIndustryTag5(String industryTag5) {
		this.industryTag5 = industryTag5 == null ? null : industryTag5.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.create_time
	 * @return  the value of ad_pool.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.create_time
	 * @param createTime  the value for ad_pool.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ad_pool.status
	 * @return  the value of ad_pool.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ad_pool.status
	 * @param status  the value for ad_pool.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}