package bz.sunlight.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bill
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public BillExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bill
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIsNull() {
			addCriterion("enterprise_id is null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIsNotNull() {
			addCriterion("enterprise_id is not null");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdEqualTo(String value) {
			addCriterion("enterprise_id =", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotEqualTo(String value) {
			addCriterion("enterprise_id <>", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdGreaterThan(String value) {
			addCriterion("enterprise_id >", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdGreaterThanOrEqualTo(String value) {
			addCriterion("enterprise_id >=", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLessThan(String value) {
			addCriterion("enterprise_id <", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLessThanOrEqualTo(String value) {
			addCriterion("enterprise_id <=", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdLike(String value) {
			addCriterion("enterprise_id like", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotLike(String value) {
			addCriterion("enterprise_id not like", value, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdIn(List<String> values) {
			addCriterion("enterprise_id in", values, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotIn(List<String> values) {
			addCriterion("enterprise_id not in", values, "enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdBetween(String value1, String value2) {
			addCriterion("enterprise_id between", value1, value2,
					"enterpriseId");
			return (Criteria) this;
		}

		public Criteria andEnterpriseIdNotBetween(String value1, String value2) {
			addCriterion("enterprise_id not between", value1, value2,
					"enterpriseId");
			return (Criteria) this;
		}

		public Criteria andCallPriceIsNull() {
			addCriterion("call_price is null");
			return (Criteria) this;
		}

		public Criteria andCallPriceIsNotNull() {
			addCriterion("call_price is not null");
			return (Criteria) this;
		}

		public Criteria andCallPriceEqualTo(Double value) {
			addCriterion("call_price =", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceNotEqualTo(Double value) {
			addCriterion("call_price <>", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceGreaterThan(Double value) {
			addCriterion("call_price >", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("call_price >=", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceLessThan(Double value) {
			addCriterion("call_price <", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceLessThanOrEqualTo(Double value) {
			addCriterion("call_price <=", value, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceIn(List<Double> values) {
			addCriterion("call_price in", values, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceNotIn(List<Double> values) {
			addCriterion("call_price not in", values, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceBetween(Double value1, Double value2) {
			addCriterion("call_price between", value1, value2, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallPriceNotBetween(Double value1, Double value2) {
			addCriterion("call_price not between", value1, value2, "callPrice");
			return (Criteria) this;
		}

		public Criteria andCallQuantityIsNull() {
			addCriterion("call_quantity is null");
			return (Criteria) this;
		}

		public Criteria andCallQuantityIsNotNull() {
			addCriterion("call_quantity is not null");
			return (Criteria) this;
		}

		public Criteria andCallQuantityEqualTo(Integer value) {
			addCriterion("call_quantity =", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityNotEqualTo(Integer value) {
			addCriterion("call_quantity <>", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityGreaterThan(Integer value) {
			addCriterion("call_quantity >", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("call_quantity >=", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityLessThan(Integer value) {
			addCriterion("call_quantity <", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("call_quantity <=", value, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityIn(List<Integer> values) {
			addCriterion("call_quantity in", values, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityNotIn(List<Integer> values) {
			addCriterion("call_quantity not in", values, "callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityBetween(Integer value1, Integer value2) {
			addCriterion("call_quantity between", value1, value2,
					"callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallQuantityNotBetween(Integer value1, Integer value2) {
			addCriterion("call_quantity not between", value1, value2,
					"callQuantity");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalIsNull() {
			addCriterion("call_subtotal is null");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalIsNotNull() {
			addCriterion("call_subtotal is not null");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalEqualTo(Double value) {
			addCriterion("call_subtotal =", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalNotEqualTo(Double value) {
			addCriterion("call_subtotal <>", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalGreaterThan(Double value) {
			addCriterion("call_subtotal >", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalGreaterThanOrEqualTo(Double value) {
			addCriterion("call_subtotal >=", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalLessThan(Double value) {
			addCriterion("call_subtotal <", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalLessThanOrEqualTo(Double value) {
			addCriterion("call_subtotal <=", value, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalIn(List<Double> values) {
			addCriterion("call_subtotal in", values, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalNotIn(List<Double> values) {
			addCriterion("call_subtotal not in", values, "callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalBetween(Double value1, Double value2) {
			addCriterion("call_subtotal between", value1, value2,
					"callSubtotal");
			return (Criteria) this;
		}

		public Criteria andCallSubtotalNotBetween(Double value1, Double value2) {
			addCriterion("call_subtotal not between", value1, value2,
					"callSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepPriceIsNull() {
			addCriterion("keep_price is null");
			return (Criteria) this;
		}

		public Criteria andKeepPriceIsNotNull() {
			addCriterion("keep_price is not null");
			return (Criteria) this;
		}

		public Criteria andKeepPriceEqualTo(Double value) {
			addCriterion("keep_price =", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceNotEqualTo(Double value) {
			addCriterion("keep_price <>", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceGreaterThan(Double value) {
			addCriterion("keep_price >", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("keep_price >=", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceLessThan(Double value) {
			addCriterion("keep_price <", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceLessThanOrEqualTo(Double value) {
			addCriterion("keep_price <=", value, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceIn(List<Double> values) {
			addCriterion("keep_price in", values, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceNotIn(List<Double> values) {
			addCriterion("keep_price not in", values, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceBetween(Double value1, Double value2) {
			addCriterion("keep_price between", value1, value2, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepPriceNotBetween(Double value1, Double value2) {
			addCriterion("keep_price not between", value1, value2, "keepPrice");
			return (Criteria) this;
		}

		public Criteria andKeepDayIsNull() {
			addCriterion("keep_day is null");
			return (Criteria) this;
		}

		public Criteria andKeepDayIsNotNull() {
			addCriterion("keep_day is not null");
			return (Criteria) this;
		}

		public Criteria andKeepDayEqualTo(Integer value) {
			addCriterion("keep_day =", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayNotEqualTo(Integer value) {
			addCriterion("keep_day <>", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayGreaterThan(Integer value) {
			addCriterion("keep_day >", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayGreaterThanOrEqualTo(Integer value) {
			addCriterion("keep_day >=", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayLessThan(Integer value) {
			addCriterion("keep_day <", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayLessThanOrEqualTo(Integer value) {
			addCriterion("keep_day <=", value, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayIn(List<Integer> values) {
			addCriterion("keep_day in", values, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayNotIn(List<Integer> values) {
			addCriterion("keep_day not in", values, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayBetween(Integer value1, Integer value2) {
			addCriterion("keep_day between", value1, value2, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepDayNotBetween(Integer value1, Integer value2) {
			addCriterion("keep_day not between", value1, value2, "keepDay");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalIsNull() {
			addCriterion("keep_subtotal is null");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalIsNotNull() {
			addCriterion("keep_subtotal is not null");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalEqualTo(Double value) {
			addCriterion("keep_subtotal =", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalNotEqualTo(Double value) {
			addCriterion("keep_subtotal <>", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalGreaterThan(Double value) {
			addCriterion("keep_subtotal >", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalGreaterThanOrEqualTo(Double value) {
			addCriterion("keep_subtotal >=", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalLessThan(Double value) {
			addCriterion("keep_subtotal <", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalLessThanOrEqualTo(Double value) {
			addCriterion("keep_subtotal <=", value, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalIn(List<Double> values) {
			addCriterion("keep_subtotal in", values, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalNotIn(List<Double> values) {
			addCriterion("keep_subtotal not in", values, "keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalBetween(Double value1, Double value2) {
			addCriterion("keep_subtotal between", value1, value2,
					"keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andKeepSubtotalNotBetween(Double value1, Double value2) {
			addCriterion("keep_subtotal not between", value1, value2,
					"keepSubtotal");
			return (Criteria) this;
		}

		public Criteria andBaseCostIsNull() {
			addCriterion("base_cost is null");
			return (Criteria) this;
		}

		public Criteria andBaseCostIsNotNull() {
			addCriterion("base_cost is not null");
			return (Criteria) this;
		}

		public Criteria andBaseCostEqualTo(Double value) {
			addCriterion("base_cost =", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostNotEqualTo(Double value) {
			addCriterion("base_cost <>", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostGreaterThan(Double value) {
			addCriterion("base_cost >", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostGreaterThanOrEqualTo(Double value) {
			addCriterion("base_cost >=", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostLessThan(Double value) {
			addCriterion("base_cost <", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostLessThanOrEqualTo(Double value) {
			addCriterion("base_cost <=", value, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostIn(List<Double> values) {
			addCriterion("base_cost in", values, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostNotIn(List<Double> values) {
			addCriterion("base_cost not in", values, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostBetween(Double value1, Double value2) {
			addCriterion("base_cost between", value1, value2, "baseCost");
			return (Criteria) this;
		}

		public Criteria andBaseCostNotBetween(Double value1, Double value2) {
			addCriterion("base_cost not between", value1, value2, "baseCost");
			return (Criteria) this;
		}

		public Criteria andSeatPriceIsNull() {
			addCriterion("seat_price is null");
			return (Criteria) this;
		}

		public Criteria andSeatPriceIsNotNull() {
			addCriterion("seat_price is not null");
			return (Criteria) this;
		}

		public Criteria andSeatPriceEqualTo(Double value) {
			addCriterion("seat_price =", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceNotEqualTo(Double value) {
			addCriterion("seat_price <>", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceGreaterThan(Double value) {
			addCriterion("seat_price >", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("seat_price >=", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceLessThan(Double value) {
			addCriterion("seat_price <", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceLessThanOrEqualTo(Double value) {
			addCriterion("seat_price <=", value, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceIn(List<Double> values) {
			addCriterion("seat_price in", values, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceNotIn(List<Double> values) {
			addCriterion("seat_price not in", values, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceBetween(Double value1, Double value2) {
			addCriterion("seat_price between", value1, value2, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatPriceNotBetween(Double value1, Double value2) {
			addCriterion("seat_price not between", value1, value2, "seatPrice");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityIsNull() {
			addCriterion("seat_quantity is null");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityIsNotNull() {
			addCriterion("seat_quantity is not null");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityEqualTo(Integer value) {
			addCriterion("seat_quantity =", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityNotEqualTo(Integer value) {
			addCriterion("seat_quantity <>", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityGreaterThan(Integer value) {
			addCriterion("seat_quantity >", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("seat_quantity >=", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityLessThan(Integer value) {
			addCriterion("seat_quantity <", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("seat_quantity <=", value, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityIn(List<Integer> values) {
			addCriterion("seat_quantity in", values, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityNotIn(List<Integer> values) {
			addCriterion("seat_quantity not in", values, "seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityBetween(Integer value1, Integer value2) {
			addCriterion("seat_quantity between", value1, value2,
					"seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatQuantityNotBetween(Integer value1, Integer value2) {
			addCriterion("seat_quantity not between", value1, value2,
					"seatQuantity");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalIsNull() {
			addCriterion("seat_subtotal is null");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalIsNotNull() {
			addCriterion("seat_subtotal is not null");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalEqualTo(Double value) {
			addCriterion("seat_subtotal =", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalNotEqualTo(Double value) {
			addCriterion("seat_subtotal <>", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalGreaterThan(Double value) {
			addCriterion("seat_subtotal >", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalGreaterThanOrEqualTo(Double value) {
			addCriterion("seat_subtotal >=", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalLessThan(Double value) {
			addCriterion("seat_subtotal <", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalLessThanOrEqualTo(Double value) {
			addCriterion("seat_subtotal <=", value, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalIn(List<Double> values) {
			addCriterion("seat_subtotal in", values, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalNotIn(List<Double> values) {
			addCriterion("seat_subtotal not in", values, "seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalBetween(Double value1, Double value2) {
			addCriterion("seat_subtotal between", value1, value2,
					"seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andSeatSubtotalNotBetween(Double value1, Double value2) {
			addCriterion("seat_subtotal not between", value1, value2,
					"seatSubtotal");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIsNull() {
			addCriterion("total_amount is null");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIsNotNull() {
			addCriterion("total_amount is not null");
			return (Criteria) this;
		}

		public Criteria andTotalAmountEqualTo(Double value) {
			addCriterion("total_amount =", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotEqualTo(Double value) {
			addCriterion("total_amount <>", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountGreaterThan(Double value) {
			addCriterion("total_amount >", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountGreaterThanOrEqualTo(Double value) {
			addCriterion("total_amount >=", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountLessThan(Double value) {
			addCriterion("total_amount <", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountLessThanOrEqualTo(Double value) {
			addCriterion("total_amount <=", value, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountIn(List<Double> values) {
			addCriterion("total_amount in", values, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotIn(List<Double> values) {
			addCriterion("total_amount not in", values, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountBetween(Double value1, Double value2) {
			addCriterion("total_amount between", value1, value2, "totalAmount");
			return (Criteria) this;
		}

		public Criteria andTotalAmountNotBetween(Double value1, Double value2) {
			addCriterion("total_amount not between", value1, value2,
					"totalAmount");
			return (Criteria) this;
		}

		public Criteria andBillDateIsNull() {
			addCriterion("bill_date is null");
			return (Criteria) this;
		}

		public Criteria andBillDateIsNotNull() {
			addCriterion("bill_date is not null");
			return (Criteria) this;
		}

		public Criteria andBillDateEqualTo(Date value) {
			addCriterion("bill_date =", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateNotEqualTo(Date value) {
			addCriterion("bill_date <>", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateGreaterThan(Date value) {
			addCriterion("bill_date >", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateGreaterThanOrEqualTo(Date value) {
			addCriterion("bill_date >=", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateLessThan(Date value) {
			addCriterion("bill_date <", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateLessThanOrEqualTo(Date value) {
			addCriterion("bill_date <=", value, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateIn(List<Date> values) {
			addCriterion("bill_date in", values, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateNotIn(List<Date> values) {
			addCriterion("bill_date not in", values, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateBetween(Date value1, Date value2) {
			addCriterion("bill_date between", value1, value2, "billDate");
			return (Criteria) this;
		}

		public Criteria andBillDateNotBetween(Date value1, Date value2) {
			addCriterion("bill_date not between", value1, value2, "billDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNull() {
			addCriterion("start_date is null");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNotNull() {
			addCriterion("start_date is not null");
			return (Criteria) this;
		}

		public Criteria andStartDateEqualTo(Date value) {
			addCriterion("start_date =", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotEqualTo(Date value) {
			addCriterion("start_date <>", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThan(Date value) {
			addCriterion("start_date >", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
			addCriterion("start_date >=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThan(Date value) {
			addCriterion("start_date <", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThanOrEqualTo(Date value) {
			addCriterion("start_date <=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIn(List<Date> values) {
			addCriterion("start_date in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotIn(List<Date> values) {
			addCriterion("start_date not in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateBetween(Date value1, Date value2) {
			addCriterion("start_date between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotBetween(Date value1, Date value2) {
			addCriterion("start_date not between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterion("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterion("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterion("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterion("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterion("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterion("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterion("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterion("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterion("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andYearIsNull() {
			addCriterion("year is null");
			return (Criteria) this;
		}

		public Criteria andYearIsNotNull() {
			addCriterion("year is not null");
			return (Criteria) this;
		}

		public Criteria andYearEqualTo(String value) {
			addCriterion("year =", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotEqualTo(String value) {
			addCriterion("year <>", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearGreaterThan(String value) {
			addCriterion("year >", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearGreaterThanOrEqualTo(String value) {
			addCriterion("year >=", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLessThan(String value) {
			addCriterion("year <", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLessThanOrEqualTo(String value) {
			addCriterion("year <=", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearLike(String value) {
			addCriterion("year like", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotLike(String value) {
			addCriterion("year not like", value, "year");
			return (Criteria) this;
		}

		public Criteria andYearIn(List<String> values) {
			addCriterion("year in", values, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotIn(List<String> values) {
			addCriterion("year not in", values, "year");
			return (Criteria) this;
		}

		public Criteria andYearBetween(String value1, String value2) {
			addCriterion("year between", value1, value2, "year");
			return (Criteria) this;
		}

		public Criteria andYearNotBetween(String value1, String value2) {
			addCriterion("year not between", value1, value2, "year");
			return (Criteria) this;
		}

		public Criteria andMonthIsNull() {
			addCriterion("month is null");
			return (Criteria) this;
		}

		public Criteria andMonthIsNotNull() {
			addCriterion("month is not null");
			return (Criteria) this;
		}

		public Criteria andMonthEqualTo(String value) {
			addCriterion("month =", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthNotEqualTo(String value) {
			addCriterion("month <>", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthGreaterThan(String value) {
			addCriterion("month >", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthGreaterThanOrEqualTo(String value) {
			addCriterion("month >=", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthLessThan(String value) {
			addCriterion("month <", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthLessThanOrEqualTo(String value) {
			addCriterion("month <=", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthLike(String value) {
			addCriterion("month like", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthNotLike(String value) {
			addCriterion("month not like", value, "month");
			return (Criteria) this;
		}

		public Criteria andMonthIn(List<String> values) {
			addCriterion("month in", values, "month");
			return (Criteria) this;
		}

		public Criteria andMonthNotIn(List<String> values) {
			addCriterion("month not in", values, "month");
			return (Criteria) this;
		}

		public Criteria andMonthBetween(String value1, String value2) {
			addCriterion("month between", value1, value2, "month");
			return (Criteria) this;
		}

		public Criteria andMonthNotBetween(String value1, String value2) {
			addCriterion("month not between", value1, value2, "month");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityIsNull() {
			addCriterion("base_call_quantity is null");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityIsNotNull() {
			addCriterion("base_call_quantity is not null");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityEqualTo(Integer value) {
			addCriterion("base_call_quantity =", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityNotEqualTo(Integer value) {
			addCriterion("base_call_quantity <>", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityGreaterThan(Integer value) {
			addCriterion("base_call_quantity >", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("base_call_quantity >=", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityLessThan(Integer value) {
			addCriterion("base_call_quantity <", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("base_call_quantity <=", value, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityIn(List<Integer> values) {
			addCriterion("base_call_quantity in", values, "baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityNotIn(List<Integer> values) {
			addCriterion("base_call_quantity not in", values,
					"baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityBetween(Integer value1,
				Integer value2) {
			addCriterion("base_call_quantity between", value1, value2,
					"baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseCallQuantityNotBetween(Integer value1,
				Integer value2) {
			addCriterion("base_call_quantity not between", value1, value2,
					"baseCallQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityIsNull() {
			addCriterion("base_seat_quantity is null");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityIsNotNull() {
			addCriterion("base_seat_quantity is not null");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityEqualTo(Integer value) {
			addCriterion("base_seat_quantity =", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityNotEqualTo(Integer value) {
			addCriterion("base_seat_quantity <>", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityGreaterThan(Integer value) {
			addCriterion("base_seat_quantity >", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("base_seat_quantity >=", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityLessThan(Integer value) {
			addCriterion("base_seat_quantity <", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("base_seat_quantity <=", value, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityIn(List<Integer> values) {
			addCriterion("base_seat_quantity in", values, "baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityNotIn(List<Integer> values) {
			addCriterion("base_seat_quantity not in", values,
					"baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityBetween(Integer value1,
				Integer value2) {
			addCriterion("base_seat_quantity between", value1, value2,
					"baseSeatQuantity");
			return (Criteria) this;
		}

		public Criteria andBaseSeatQuantityNotBetween(Integer value1,
				Integer value2) {
			addCriterion("base_seat_quantity not between", value1, value2,
					"baseSeatQuantity");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bill
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}