package bz.sunlight.entity;

import java.util.Date;

public class Bill {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.code
	 * @mbggenerated
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.call_price
	 * @mbggenerated
	 */
	private Double callPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.call_quantity
	 * @mbggenerated
	 */
	private Integer callQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.call_subtotal
	 * @mbggenerated
	 */
	private Double callSubtotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.keep_price
	 * @mbggenerated
	 */
	private Double keepPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.keep_day
	 * @mbggenerated
	 */
	private Integer keepDay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.keep_subtotal
	 * @mbggenerated
	 */
	private Double keepSubtotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.base_cost
	 * @mbggenerated
	 */
	private Double baseCost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.seat_price
	 * @mbggenerated
	 */
	private Double seatPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.seat_quantity
	 * @mbggenerated
	 */
	private Integer seatQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.seat_subtotal
	 * @mbggenerated
	 */
	private Double seatSubtotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.total_amount
	 * @mbggenerated
	 */
	private Double totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.bill_date
	 * @mbggenerated
	 */
	private Date billDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.start_date
	 * @mbggenerated
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.end_date
	 * @mbggenerated
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.year
	 * @mbggenerated
	 */
	private String year;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.month
	 * @mbggenerated
	 */
	private String month;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.base_call_quantity
	 * @mbggenerated
	 */
	private Integer baseCallQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bill.base_seat_quantity
	 * @mbggenerated
	 */
	private Integer baseSeatQuantity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.id
	 * @return  the value of bill.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.id
	 * @param id  the value for bill.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.code
	 * @return  the value of bill.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.code
	 * @param code  the value for bill.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.enterprise_id
	 * @return  the value of bill.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.enterprise_id
	 * @param enterpriseId  the value for bill.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.call_price
	 * @return  the value of bill.call_price
	 * @mbggenerated
	 */
	public Double getCallPrice() {
		return callPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.call_price
	 * @param callPrice  the value for bill.call_price
	 * @mbggenerated
	 */
	public void setCallPrice(Double callPrice) {
		this.callPrice = callPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.call_quantity
	 * @return  the value of bill.call_quantity
	 * @mbggenerated
	 */
	public Integer getCallQuantity() {
		return callQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.call_quantity
	 * @param callQuantity  the value for bill.call_quantity
	 * @mbggenerated
	 */
	public void setCallQuantity(Integer callQuantity) {
		this.callQuantity = callQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.call_subtotal
	 * @return  the value of bill.call_subtotal
	 * @mbggenerated
	 */
	public Double getCallSubtotal() {
		return callSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.call_subtotal
	 * @param callSubtotal  the value for bill.call_subtotal
	 * @mbggenerated
	 */
	public void setCallSubtotal(Double callSubtotal) {
		this.callSubtotal = callSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.keep_price
	 * @return  the value of bill.keep_price
	 * @mbggenerated
	 */
	public Double getKeepPrice() {
		return keepPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.keep_price
	 * @param keepPrice  the value for bill.keep_price
	 * @mbggenerated
	 */
	public void setKeepPrice(Double keepPrice) {
		this.keepPrice = keepPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.keep_day
	 * @return  the value of bill.keep_day
	 * @mbggenerated
	 */
	public Integer getKeepDay() {
		return keepDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.keep_day
	 * @param keepDay  the value for bill.keep_day
	 * @mbggenerated
	 */
	public void setKeepDay(Integer keepDay) {
		this.keepDay = keepDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.keep_subtotal
	 * @return  the value of bill.keep_subtotal
	 * @mbggenerated
	 */
	public Double getKeepSubtotal() {
		return keepSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.keep_subtotal
	 * @param keepSubtotal  the value for bill.keep_subtotal
	 * @mbggenerated
	 */
	public void setKeepSubtotal(Double keepSubtotal) {
		this.keepSubtotal = keepSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.base_cost
	 * @return  the value of bill.base_cost
	 * @mbggenerated
	 */
	public Double getBaseCost() {
		return baseCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.base_cost
	 * @param baseCost  the value for bill.base_cost
	 * @mbggenerated
	 */
	public void setBaseCost(Double baseCost) {
		this.baseCost = baseCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.seat_price
	 * @return  the value of bill.seat_price
	 * @mbggenerated
	 */
	public Double getSeatPrice() {
		return seatPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.seat_price
	 * @param seatPrice  the value for bill.seat_price
	 * @mbggenerated
	 */
	public void setSeatPrice(Double seatPrice) {
		this.seatPrice = seatPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.seat_quantity
	 * @return  the value of bill.seat_quantity
	 * @mbggenerated
	 */
	public Integer getSeatQuantity() {
		return seatQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.seat_quantity
	 * @param seatQuantity  the value for bill.seat_quantity
	 * @mbggenerated
	 */
	public void setSeatQuantity(Integer seatQuantity) {
		this.seatQuantity = seatQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.seat_subtotal
	 * @return  the value of bill.seat_subtotal
	 * @mbggenerated
	 */
	public Double getSeatSubtotal() {
		return seatSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.seat_subtotal
	 * @param seatSubtotal  the value for bill.seat_subtotal
	 * @mbggenerated
	 */
	public void setSeatSubtotal(Double seatSubtotal) {
		this.seatSubtotal = seatSubtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.total_amount
	 * @return  the value of bill.total_amount
	 * @mbggenerated
	 */
	public Double getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.total_amount
	 * @param totalAmount  the value for bill.total_amount
	 * @mbggenerated
	 */
	public void setTotalAmount(Double totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.bill_date
	 * @return  the value of bill.bill_date
	 * @mbggenerated
	 */
	public Date getBillDate() {
		return billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.bill_date
	 * @param billDate  the value for bill.bill_date
	 * @mbggenerated
	 */
	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.start_date
	 * @return  the value of bill.start_date
	 * @mbggenerated
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.start_date
	 * @param startDate  the value for bill.start_date
	 * @mbggenerated
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.end_date
	 * @return  the value of bill.end_date
	 * @mbggenerated
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.end_date
	 * @param endDate  the value for bill.end_date
	 * @mbggenerated
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.year
	 * @return  the value of bill.year
	 * @mbggenerated
	 */
	public String getYear() {
		return year;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.year
	 * @param year  the value for bill.year
	 * @mbggenerated
	 */
	public void setYear(String year) {
		this.year = year == null ? null : year.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.month
	 * @return  the value of bill.month
	 * @mbggenerated
	 */
	public String getMonth() {
		return month;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.month
	 * @param month  the value for bill.month
	 * @mbggenerated
	 */
	public void setMonth(String month) {
		this.month = month == null ? null : month.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.base_call_quantity
	 * @return  the value of bill.base_call_quantity
	 * @mbggenerated
	 */
	public Integer getBaseCallQuantity() {
		return baseCallQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.base_call_quantity
	 * @param baseCallQuantity  the value for bill.base_call_quantity
	 * @mbggenerated
	 */
	public void setBaseCallQuantity(Integer baseCallQuantity) {
		this.baseCallQuantity = baseCallQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bill.base_seat_quantity
	 * @return  the value of bill.base_seat_quantity
	 * @mbggenerated
	 */
	public Integer getBaseSeatQuantity() {
		return baseSeatQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bill.base_seat_quantity
	 * @param baseSeatQuantity  the value for bill.base_seat_quantity
	 * @mbggenerated
	 */
	public void setBaseSeatQuantity(Integer baseSeatQuantity) {
		this.baseSeatQuantity = baseSeatQuantity;
	}
}