package bz.sunlight.entity;

import java.util.Date;

public class BusinessQueue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.business_id
     *
     * @mbggenerated
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.handle_status
     *
     * @mbggenerated
     */
    private Short handleStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_queue.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.id
     *
     * @return the value of business_queue.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.id
     *
     * @param id the value for business_queue.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.business_id
     *
     * @return the value of business_queue.business_id
     *
     * @mbggenerated
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.business_id
     *
     * @param businessId the value for business_queue.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.type
     *
     * @return the value of business_queue.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.type
     *
     * @param type the value for business_queue.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.handle_status
     *
     * @return the value of business_queue.handle_status
     *
     * @mbggenerated
     */
    public Short getHandleStatus() {
        return handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.handle_status
     *
     * @param handleStatus the value for business_queue.handle_status
     *
     * @mbggenerated
     */
    public void setHandleStatus(Short handleStatus) {
        this.handleStatus = handleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.create_time
     *
     * @return the value of business_queue.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.create_time
     *
     * @param createTime the value for business_queue.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_queue.modify_time
     *
     * @return the value of business_queue.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_queue.modify_time
     *
     * @param modifyTime the value for business_queue.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}