package bz.sunlight.entity;

import java.util.Date;

public class CallResponseMsg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_response_msg.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_response_msg.session_id
	 * @mbggenerated
	 */
	private String sessionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_response_msg.user_info_id
	 * @mbggenerated
	 */
	private String userInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_response_msg.secret_id
	 * @mbggenerated
	 */
	private String secretId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_response_msg.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_response_msg.id
	 * @return  the value of call_response_msg.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_response_msg.id
	 * @param id  the value for call_response_msg.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_response_msg.session_id
	 * @return  the value of call_response_msg.session_id
	 * @mbggenerated
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_response_msg.session_id
	 * @param sessionId  the value for call_response_msg.session_id
	 * @mbggenerated
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId == null ? null : sessionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_response_msg.user_info_id
	 * @return  the value of call_response_msg.user_info_id
	 * @mbggenerated
	 */
	public String getUserInfoId() {
		return userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_response_msg.user_info_id
	 * @param userInfoId  the value for call_response_msg.user_info_id
	 * @mbggenerated
	 */
	public void setUserInfoId(String userInfoId) {
		this.userInfoId = userInfoId == null ? null : userInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_response_msg.secret_id
	 * @return  the value of call_response_msg.secret_id
	 * @mbggenerated
	 */
	public String getSecretId() {
		return secretId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_response_msg.secret_id
	 * @param secretId  the value for call_response_msg.secret_id
	 * @mbggenerated
	 */
	public void setSecretId(String secretId) {
		this.secretId = secretId == null ? null : secretId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_response_msg.create_time
	 * @return  the value of call_response_msg.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_response_msg.create_time
	 * @param createTime  the value for call_response_msg.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}