package bz.sunlight.entity;

import java.util.Date;

public class CallRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.secret_id
	 * @mbggenerated
	 */
	private String secretId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.user_info_id
	 * @mbggenerated
	 */
	private String userInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.session_id
	 * @mbggenerated
	 */
	private String sessionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.record
	 * @mbggenerated
	 */
	private String record;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.language_trick_id
	 * @mbggenerated
	 */
	private String languageTrickId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.call_result
	 * @mbggenerated
	 */
	private Short callResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.call_time
	 * @mbggenerated
	 */
	private Date callTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.connect_time
	 * @mbggenerated
	 */
	private Date connectTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.hang_up_time
	 * @mbggenerated
	 */
	private Date hangUpTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.custom_properties_id1
	 * @mbggenerated
	 */
	private String customPropertiesId1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.custom_properties_id2
	 * @mbggenerated
	 */
	private String customPropertiesId2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.custom_properties_3
	 * @mbggenerated
	 */
	private String customProperties3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column call_record.remark
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.id
	 * @return  the value of call_record.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.id
	 * @param id  the value for call_record.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.secret_id
	 * @return  the value of call_record.secret_id
	 * @mbggenerated
	 */
	public String getSecretId() {
		return secretId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.secret_id
	 * @param secretId  the value for call_record.secret_id
	 * @mbggenerated
	 */
	public void setSecretId(String secretId) {
		this.secretId = secretId == null ? null : secretId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.user_info_id
	 * @return  the value of call_record.user_info_id
	 * @mbggenerated
	 */
	public String getUserInfoId() {
		return userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.user_info_id
	 * @param userInfoId  the value for call_record.user_info_id
	 * @mbggenerated
	 */
	public void setUserInfoId(String userInfoId) {
		this.userInfoId = userInfoId == null ? null : userInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.enterprise_id
	 * @return  the value of call_record.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.enterprise_id
	 * @param enterpriseId  the value for call_record.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.session_id
	 * @return  the value of call_record.session_id
	 * @mbggenerated
	 */
	public String getSessionId() {
		return sessionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.session_id
	 * @param sessionId  the value for call_record.session_id
	 * @mbggenerated
	 */
	public void setSessionId(String sessionId) {
		this.sessionId = sessionId == null ? null : sessionId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.record
	 * @return  the value of call_record.record
	 * @mbggenerated
	 */
	public String getRecord() {
		return record;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.record
	 * @param record  the value for call_record.record
	 * @mbggenerated
	 */
	public void setRecord(String record) {
		this.record = record == null ? null : record.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.language_trick_id
	 * @return  the value of call_record.language_trick_id
	 * @mbggenerated
	 */
	public String getLanguageTrickId() {
		return languageTrickId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.language_trick_id
	 * @param languageTrickId  the value for call_record.language_trick_id
	 * @mbggenerated
	 */
	public void setLanguageTrickId(String languageTrickId) {
		this.languageTrickId = languageTrickId == null ? null : languageTrickId
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.call_result
	 * @return  the value of call_record.call_result
	 * @mbggenerated
	 */
	public Short getCallResult() {
		return callResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.call_result
	 * @param callResult  the value for call_record.call_result
	 * @mbggenerated
	 */
	public void setCallResult(Short callResult) {
		this.callResult = callResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.call_time
	 * @return  the value of call_record.call_time
	 * @mbggenerated
	 */
	public Date getCallTime() {
		return callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.call_time
	 * @param callTime  the value for call_record.call_time
	 * @mbggenerated
	 */
	public void setCallTime(Date callTime) {
		this.callTime = callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.connect_time
	 * @return  the value of call_record.connect_time
	 * @mbggenerated
	 */
	public Date getConnectTime() {
		return connectTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.connect_time
	 * @param connectTime  the value for call_record.connect_time
	 * @mbggenerated
	 */
	public void setConnectTime(Date connectTime) {
		this.connectTime = connectTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.hang_up_time
	 * @return  the value of call_record.hang_up_time
	 * @mbggenerated
	 */
	public Date getHangUpTime() {
		return hangUpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.hang_up_time
	 * @param hangUpTime  the value for call_record.hang_up_time
	 * @mbggenerated
	 */
	public void setHangUpTime(Date hangUpTime) {
		this.hangUpTime = hangUpTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.status
	 * @return  the value of call_record.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.status
	 * @param status  the value for call_record.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.create_time
	 * @return  the value of call_record.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.create_time
	 * @param createTime  the value for call_record.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.custom_properties_id1
	 * @return  the value of call_record.custom_properties_id1
	 * @mbggenerated
	 */
	public String getCustomPropertiesId1() {
		return customPropertiesId1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.custom_properties_id1
	 * @param customPropertiesId1  the value for call_record.custom_properties_id1
	 * @mbggenerated
	 */
	public void setCustomPropertiesId1(String customPropertiesId1) {
		this.customPropertiesId1 = customPropertiesId1 == null ? null
				: customPropertiesId1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.custom_properties_id2
	 * @return  the value of call_record.custom_properties_id2
	 * @mbggenerated
	 */
	public String getCustomPropertiesId2() {
		return customPropertiesId2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.custom_properties_id2
	 * @param customPropertiesId2  the value for call_record.custom_properties_id2
	 * @mbggenerated
	 */
	public void setCustomPropertiesId2(String customPropertiesId2) {
		this.customPropertiesId2 = customPropertiesId2 == null ? null
				: customPropertiesId2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.custom_properties_3
	 * @return  the value of call_record.custom_properties_3
	 * @mbggenerated
	 */
	public String getCustomProperties3() {
		return customProperties3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.custom_properties_3
	 * @param customProperties3  the value for call_record.custom_properties_3
	 * @mbggenerated
	 */
	public void setCustomProperties3(String customProperties3) {
		this.customProperties3 = customProperties3 == null ? null
				: customProperties3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column call_record.remark
	 * @return  the value of call_record.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column call_record.remark
	 * @param remark  the value for call_record.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}