package bz.sunlight.entity;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

public class Customer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.secret_id
	 * @mbggenerated
	 */
	private String secretId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.gender
	 * @mbggenerated
	 */
	private Short gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.tel
	 * @mbggenerated
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.appointment_date
	 * @mbggenerated
	 */
	private Date appointmentDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.intention_vehicle
	 * @mbggenerated
	 */
	private String intentionVehicle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.user_info_id
	 * @mbggenerated
	 */
	private String userInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customer.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.id
	 * @return  the value of customer.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.id
	 * @param id  the value for customer.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.secret_id
	 * @return  the value of customer.secret_id
	 * @mbggenerated
	 */
	public String getSecretId() {
		return secretId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.secret_id
	 * @param secretId  the value for customer.secret_id
	 * @mbggenerated
	 */
	public void setSecretId(String secretId) {
		this.secretId = secretId == null ? null : secretId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.name
	 * @return  the value of customer.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.name
	 * @param name  the value for customer.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.gender
	 * @return  the value of customer.gender
	 * @mbggenerated
	 */
	public Short getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.gender
	 * @param gender  the value for customer.gender
	 * @mbggenerated
	 */
	public void setGender(Short gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.mobile
	 * @return  the value of customer.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.mobile
	 * @param mobile  the value for customer.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.tel
	 * @return  the value of customer.tel
	 * @mbggenerated
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.tel
	 * @param tel  the value for customer.tel
	 * @mbggenerated
	 */
	public void setTel(String tel) {
		this.tel = tel == null ? null : tel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.appointment_date
	 * @return  the value of customer.appointment_date
	 * @mbggenerated
	 */
	public Date getAppointmentDate() {
		return appointmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.appointment_date
	 * @param appointmentDate  the value for customer.appointment_date
	 * @mbggenerated
	 */
	public void setAppointmentDate(Date appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.intention_vehicle
	 * @return  the value of customer.intention_vehicle
	 * @mbggenerated
	 */
	public String getIntentionVehicle() {
		return intentionVehicle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.intention_vehicle
	 * @param intentionVehicle  the value for customer.intention_vehicle
	 * @mbggenerated
	 */
	public void setIntentionVehicle(String intentionVehicle) {
		this.intentionVehicle = intentionVehicle == null ? null
				: intentionVehicle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.remark
	 * @return  the value of customer.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.remark
	 * @param remark  the value for customer.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.user_info_id
	 * @return  the value of customer.user_info_id
	 * @mbggenerated
	 */
	public String getUserInfoId() {
		return userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.user_info_id
	 * @param userInfoId  the value for customer.user_info_id
	 * @mbggenerated
	 */
	public void setUserInfoId(String userInfoId) {
		this.userInfoId = userInfoId == null ? null : userInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customer.enterprise_id
	 * @return  the value of customer.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customer.enterprise_id
	 * @param enterpriseId  the value for customer.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}
}