package bz.sunlight.entity;

import java.util.ArrayList;
import java.util.List;

public class DefaultLangugeTrickExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public DefaultLangugeTrickExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdIsNull() {
			addCriterion("language_trick_id is null");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdIsNotNull() {
			addCriterion("language_trick_id is not null");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdEqualTo(String value) {
			addCriterion("language_trick_id =", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdNotEqualTo(String value) {
			addCriterion("language_trick_id <>", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdGreaterThan(String value) {
			addCriterion("language_trick_id >", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdGreaterThanOrEqualTo(String value) {
			addCriterion("language_trick_id >=", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdLessThan(String value) {
			addCriterion("language_trick_id <", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdLessThanOrEqualTo(String value) {
			addCriterion("language_trick_id <=", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdLike(String value) {
			addCriterion("language_trick_id like", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdNotLike(String value) {
			addCriterion("language_trick_id not like", value, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdIn(List<String> values) {
			addCriterion("language_trick_id in", values, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdNotIn(List<String> values) {
			addCriterion("language_trick_id not in", values, "languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdBetween(String value1, String value2) {
			addCriterion("language_trick_id between", value1, value2,
					"languageTrickId");
			return (Criteria) this;
		}

		public Criteria andLanguageTrickIdNotBetween(String value1,
				String value2) {
			addCriterion("language_trick_id not between", value1, value2,
					"languageTrickId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdIsNull() {
			addCriterion("user_info_id is null");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdIsNotNull() {
			addCriterion("user_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdEqualTo(String value) {
			addCriterion("user_info_id =", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdNotEqualTo(String value) {
			addCriterion("user_info_id <>", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdGreaterThan(String value) {
			addCriterion("user_info_id >", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdGreaterThanOrEqualTo(String value) {
			addCriterion("user_info_id >=", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdLessThan(String value) {
			addCriterion("user_info_id <", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdLessThanOrEqualTo(String value) {
			addCriterion("user_info_id <=", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdLike(String value) {
			addCriterion("user_info_id like", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdNotLike(String value) {
			addCriterion("user_info_id not like", value, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdIn(List<String> values) {
			addCriterion("user_info_id in", values, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdNotIn(List<String> values) {
			addCriterion("user_info_id not in", values, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdBetween(String value1, String value2) {
			addCriterion("user_info_id between", value1, value2, "userInfoId");
			return (Criteria) this;
		}

		public Criteria andUserInfoIdNotBetween(String value1, String value2) {
			addCriterion("user_info_id not between", value1, value2,
					"userInfoId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table default_languge_trick
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table default_languge_trick
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}