package bz.sunlight.dao;



import bz.sunlight.entity.Vehiclecategory;
import bz.sunlight.entity.VehiclecategoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VehiclecategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int countByExample(VehiclecategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int deleteByExample(VehiclecategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int insert(Vehiclecategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int insertSelective(Vehiclecategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	List<Vehiclecategory> selectByExample(VehiclecategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Vehiclecategory record,
			@Param("example") VehiclecategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table vehiclecategory
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Vehiclecategory record,
			@Param("example") VehiclecategoryExample example);
}