package bz.sunlight.dao;

import bz.sunlight.entity.Banks;
import bz.sunlight.entity.BanksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BanksMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int countByExample(BanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int deleteByExample(BanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int insert(Banks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int insertSelective(Banks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	List<Banks> selectByExample(BanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	Banks selectByPrimaryKey(Short id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Banks record,
			@Param("example") BanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Banks record,
			@Param("example") BanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Banks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Banks record);
}