package bz.sunlight.entity;

public class Banks {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banks.id
	 * @mbggenerated
	 */
	private Short id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banks.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banks.code
	 * @mbggenerated
	 */
	private String code;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banks.id
	 * @return  the value of banks.id
	 * @mbggenerated
	 */
	public Short getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banks.id
	 * @param id  the value for banks.id
	 * @mbggenerated
	 */
	public void setId(Short id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banks.name
	 * @return  the value of banks.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banks.name
	 * @param name  the value for banks.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banks.code
	 * @return  the value of banks.code
	 * @mbggenerated
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banks.code
	 * @param code  the value for banks.code
	 * @mbggenerated
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}
}