package bz.sunlight.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ConsumeRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.account
	 * @mbggenerated
	 */
	private Double account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.type
	 * @mbggenerated
	 */
	private Short type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.consume_time
	 * @mbggenerated
	 */
	private Date consumeTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.enterprise_id
	 * @mbggenerated
	 */
	private String enterpriseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.user_info_id
	 * @mbggenerated
	 */
	private String userInfoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column consume_record.current
	 * @mbggenerated
	 */
	private Double current;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.id
	 * @return  the value of consume_record.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.id
	 * @param id  the value for consume_record.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.account
	 * @return  the value of consume_record.account
	 * @mbggenerated
	 */
	public Double getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.account
	 * @param account  the value for consume_record.account
	 * @mbggenerated
	 */
	public void setAccount(Double account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.type
	 * @return  the value of consume_record.type
	 * @mbggenerated
	 */
	public Short getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.type
	 * @param type  the value for consume_record.type
	 * @mbggenerated
	 */
	public void setType(Short type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.consume_time
	 * @return  the value of consume_record.consume_time
	 * @mbggenerated
	 */
	public Date getConsumeTime() {
		return consumeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.consume_time
	 * @param consumeTime  the value for consume_record.consume_time
	 * @mbggenerated
	 */
	public void setConsumeTime(Date consumeTime) {
		this.consumeTime = consumeTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.enterprise_id
	 * @return  the value of consume_record.enterprise_id
	 * @mbggenerated
	 */
	public String getEnterpriseId() {
		return enterpriseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.enterprise_id
	 * @param enterpriseId  the value for consume_record.enterprise_id
	 * @mbggenerated
	 */
	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId == null ? null : enterpriseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.user_info_id
	 * @return  the value of consume_record.user_info_id
	 * @mbggenerated
	 */
	public String getUserInfoId() {
		return userInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.user_info_id
	 * @param userInfoId  the value for consume_record.user_info_id
	 * @mbggenerated
	 */
	public void setUserInfoId(String userInfoId) {
		this.userInfoId = userInfoId == null ? null : userInfoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column consume_record.current
	 * @return  the value of consume_record.current
	 * @mbggenerated
	 */
	public Double getCurrent() {
		return current;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column consume_record.current
	 * @param current  the value for consume_record.current
	 * @mbggenerated
	 */
	public void setCurrent(Double current) {
		this.current = current;
	}
}