package bz.sunlight.entity;

import java.util.Date;

public class GiftPackage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift_package.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift_package.amount
	 * @mbggenerated
	 */
	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift_package.gift_amount
	 * @mbggenerated
	 */
	private Double giftAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift_package.status
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column gift_package.create_time
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift_package.id
	 * @return  the value of gift_package.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift_package.id
	 * @param id  the value for gift_package.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift_package.amount
	 * @return  the value of gift_package.amount
	 * @mbggenerated
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift_package.amount
	 * @param amount  the value for gift_package.amount
	 * @mbggenerated
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift_package.gift_amount
	 * @return  the value of gift_package.gift_amount
	 * @mbggenerated
	 */
	public Double getGiftAmount() {
		return giftAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift_package.gift_amount
	 * @param giftAmount  the value for gift_package.gift_amount
	 * @mbggenerated
	 */
	public void setGiftAmount(Double giftAmount) {
		this.giftAmount = giftAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift_package.status
	 * @return  the value of gift_package.status
	 * @mbggenerated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift_package.status
	 * @param status  the value for gift_package.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column gift_package.create_time
	 * @return  the value of gift_package.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column gift_package.create_time
	 * @param createTime  the value for gift_package.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
	@Override
	public boolean equals(Object obj) {
		// TODO Auto-generated method stub
		GiftPackage gift=(GiftPackage)obj;
		if(gift.getAmount()==this.amount){
			return true;
		}
		return false;
	}
}